### PR TITLE
Switch to Go modules

### PR DESCRIPTION
**Pull request by radu-matei**
We should not merge until we have working (and passing) CI.

Edit: it turns out Circle is actually running the builds, but not reporting back to GitHub because maybe it's not authorized - https://circleci.com/gh/cnabio/cnab-to-oci/300

### CODE REVIEW

**Comment by radu-matei** [comment]
#98 is being hit here.

**Comment by carolynvs** [comment]
I don't have permission in circle to enable this, but I can approve it on the GH side once requested.

https://circleci.com/docs/2.0/enable-checks/

I think that's what needs to happen, want to give it a go @silvin-lubecki ?

**Comment by vdice** [comment]
@radu-matei I believe I've enabled the circleci app now; can you try re-triggering with a fresh push?

**Comment by silvin-lubecki** [comment]
The build failed 🤔 
```
--- FAIL: TestPromisesScheduleErroredDontBlockDontRun (0.00s)
    promises_test.go:87: assertion failed: expected an error, got nil
```

**Comment by radu-matei** [comment]
@silvin-lubecki - and there's another transient error, #98.
We should definitely not merge until we fix them.

**Comment by radu-matei** [comment]
Rebased on top of `master`, which updates the Go version in CI.
This means the build is now passing, and given that #98 also occurs in current `master`, and so is not introduced by this PR, I think we should merge it and track #98 separately (we already do that).

Thoughts?

**Pull request merged**
