### PR TITLE
Use relocation map during bundle fixup

### LINKED ISSUE #108: Copy a bundle with a relocation map to another registry
Here's the scenario that a Porter user is encountering:

1. Push a bundle to a public registry, example/mybun:v1.0.0
2. Copy the bundle to local registry, localhost:5000/mybun:v1.0.0. The copy now has a relocation map that maps `example/mybun-invocation-image:v1.0.0 => localhost:5000/mybun-invocation-image:v1.0.0`.
3. Disconnect your internet connection.
4. Copy the bundle from localhost:5000/mybun:v1.0.0 to localhost:5000/newbun:v1.0.0.

The copy fails because it tries to copy the invocation image from its original location defined in the bundle, instead of copying the relocated invocation image.

I'm not sure if there is a way to make this work right now? It seems like FixupBundle should take a relocation map for the bundle, and take any relocations into account before pulling and copying images?

### PR DESCRIPTION
**Pull request by carolynvs**
I believe the relocation map was accidentally not used after `WithRelocationMap` is set, and it news up an empty relocation map before fixing the images in the bundle.

I have updated the fixup to use the relocation mapping set by the caller, and fixed the mocks in the tests to account for the new code flow. I've also tweaked the log messages so that you can see exactly which image is being pushed (i.e. pushing the relocated image instead always printing the original image name).

Fixes #108

### CODE REVIEW

**Comment by carolynvs** [comment]
So the cnab-to-oci build is currently broken. It's on go 1.13 but using the latest of tools that no longer support 1.13.  I played around with bumping to go 1.15 in this PR and ran into more issues. I'll try pinning the tools to older versions and see how that plays out, and then will open a separate PR with the fix for the build.

**Review by vdice — COMMENTED** [review]
This looks good to me!  Defer to maintainers @silvin-lubecki and @radu-matei for final approval.

**Comment by radu-matei** [comment]
CI seems to fail here:

```
# github.com/quasilyte/go-ruleguard/internal/gogrep
/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.4/internal/gogrep/match.go:677:13: undefined: strconv.ParseComplex
note: module requires Go 1.15
make: *** [Makefile:51: get-tools] Error 2

Exited with code exit status 2
```

**Review by radu-matei — APPROVED** [review]
I think this needs a rebase, then it's good to go.
Thank you!

**Comment by carolynvs** [comment]
@radu-matei Rebased!

**Pull request merged**
