### PR TITLE
Complete minimal bundle.json that needs no fixup

### PR DESCRIPTION
**Pull request by trishankatdatadog**

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Hmm, looks like that bundle is deliberately designed to need a fixup! Will add a separate file.

**Comment by radu-matei** [comment]
Would it make sense to add a note in the doc as to how the files should be used?
Thanks!

**Comment by trishankatdatadog** [comment]
Sure! Do you mean the README? Where specifically do you think would be best?

**Comment by silvin-lubecki** [comment]
@trishankatdatadog can you rebase your PR 🙏 ?

**Comment by trishankatdatadog** [comment]
@silvin-lubecki Is this ok now?

**Comment by radu-matei** [comment]
The build failure is because if #98, I still haven't figured out the reason for it, but it is definitely not introduced by this PR.

**Pull request merged**
