### PR TITLE
Rename imports to cnabio/cnab-to-oci

### PR DESCRIPTION
**Pull request by silvin-lubecki**
image

### CODE REVIEW

**Comment by carolynvs** [comment]
When we moved porter over to a new import path, it helped to have canonical import paths defined in `doc.go` files, e.g.

**doc.go**
```golang
package remotes // import "github.com/cnabio/cnab-to-oci/remotes"
```

This helped us quickly tell while updating code when we had imported/vendored accidentally from the old location and the new location. Just a suggestion that may help downstream consumers of this lib when migrating.

**Comment by silvin-lubecki** [comment]
PTAL @carolynvs

**Comment by silvin-lubecki** [comment]
Thanks @carolynvs , just added the missing `doc.go` files + squashed.

**Comment by silvin-lubecki** [comment]
Rebased

**Pull request merged**
